apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    environment: production
    provider: kustomize
  labels:
    app: ranking
  name: ranking
  namespace: production-delphi
spec:
  maxReplicas: 80
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 30
          type: Utilization
      type: Resource
  minReplicas: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ranking