apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    environment: staging
    provider: kustomize
  labels:
    app: ranking
  name: ranking
  namespace: staging-delphi
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ranking