apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    environment: production
    provider: kustomize
  labels:
    app: ranking
  name: ranking
  namespace: production-delphi
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: ranking