apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  annotations:
    environment: staging
    provider: kustomize
    tubi/enable-whitelist: enabled
  labels:
    app: grpc-ui
  name: grpc-ui
  namespace: staging-delphi
spec:
  host: grpc-ui.staging-public.tubi.io
  policies:
    - name: allow-internal-ips
      namespace: ingress-nginx
  routes:
    - action:
        pass: grpc-ui
      path: /
  upstreams:
    - name: grpc-ui
      port: 6969
      service: grpc-ui